---
 - name: Install iptables
   apt:
     name: iptables
     state: present
     update_cache: true

 - name: Track input chain
   iptables:
     chain: INPUT
     match: conntrack
     ctstate: ESTABLISHED,RELATED
     jump: ACCEPT

 - name: Track forward chain
   iptables:
     chain: FORWARD
     match: conntrack
     ctstate: ESTABLISHED,RELATED
     jump: ACCEPT

 - name: Allow incoming wireguard connections
   iptables:
     chain: INPUT
     protocol: udp
     match: udp
     destination_port: "{{ wg_port }}"
     ctstate: NEW
     jump: ACCEPT

 - name: Allow forwarding of packets that stay in the tunnel
   iptables:
     chain: FORWARD
     in_interface: wg0
     match: conntrack
     out_interface: wg0
     ctstate: NEW
     jump: ACCEPT

 - name: Do not NAT ourselves
   iptables:
     table: nat
     chain: POSTROUTING
     source: "{{ client_net_middleman_ip }}"
     jump: RETURN

 - name: Set up vpn chain NAT
   iptables:
     table: nat
     chain: POSTROUTING
     source: "{{ client_net }}.0/24"
     to_source: "{{ gate_net_middleman_ip }}"
     jump: SNAT

 - name: Install iptables-persistent
   apt:
     name: iptables-persistent
     state: present
     update_cache: true

 - name: Set up iptables persistence
   command: netfilter-persistent save
